#include <fmt/args.h>
#include <fmt/chrono.h>
#include <fmt/color.h>
#include <fmt/core.h>
#include <fmt/os.h>
#include <fmt/ostream.h>
#include <fmt/ranges.h>
#include <fmt/std.h>

#include <QDMAController.hpp>

void throughput_benchmark_print_counters(FPGACtl* fpga_ctl) {
    // Print counters, copied from code generated by Chisel project.

    // Report width 32:
    fmt::println("tlb.io.tlb_miss_count                                       : {}", fpga_ctl->readReg(512 + 400));
    fmt::println("io.c2h_cmd.[fire]                                           : {}", fpga_ctl->readReg(512 + 401));
    fmt::println("io.h2c_cmd.[fire]                                           : {}", fpga_ctl->readReg(512 + 402));
    fmt::println("io.c2h_data.[fire]                                          : {}", fpga_ctl->readReg(512 + 403));
    fmt::println("io.h2c_data.[fire]                                          : {}", fpga_ctl->readReg(512 + 404));
    fmt::println("fifo_c2h_cmd.io.out.[fire]                                  : {}", fpga_ctl->readReg(512 + 405));
    fmt::println("fifo_h2c_cmd.io.out.[fire]                                  : {}", fpga_ctl->readReg(512 + 406));
    fmt::println("fifo_c2h_data.io.out.[fire]                                 : {}", fpga_ctl->readReg(512 + 407));
    fmt::println("fifo_h2c_data.io.in.[fire]                                  : {}", fpga_ctl->readReg(512 + 408));

    // Report width 1:
    fmt::println("fifo_c2h_cmd.io.out.valid                                   : {}", (fpga_ctl->readReg(512 + 409) >> 0) & 1);
    fmt::println("fifo_c2h_cmd.io.out.ready                                   : {}", (fpga_ctl->readReg(512 + 409) >> 1) & 1);
    fmt::println("fifo_h2c_cmd.io.out.valid                                   : {}", (fpga_ctl->readReg(512 + 409) >> 2) & 1);
    fmt::println("fifo_h2c_cmd.io.out.ready                                   : {}", (fpga_ctl->readReg(512 + 409) >> 3) & 1);
    fmt::println("fifo_c2h_data.io.out.valid                                  : {}", (fpga_ctl->readReg(512 + 409) >> 4) & 1);
    fmt::println("fifo_c2h_data.io.out.ready                                  : {}", (fpga_ctl->readReg(512 + 409) >> 5) & 1);
    fmt::println("fifo_h2c_data.io.in.valid                                   : {}", (fpga_ctl->readReg(512 + 409) >> 6) & 1);
    fmt::println("fifo_h2c_data.io.in.ready                                   : {}", (fpga_ctl->readReg(512 + 409) >> 7) & 1);
}

void reset_counters(FPGACtl* fpga_ctl) {
    fpga_ctl->writeReg(14, 1);
    fpga_ctl->writeReg(14, 0);
}


void random_benchmark_print_counters(FPGACtl *fpga_ctl) {
    // Print counters, copied from code generated by Chisel project.
    
    //Report width 32:
    fmt::println("tlb.io.tlb_miss_count                                       : {}", fpga_ctl->readReg(512+300));
    fmt::println("io.c2h_cmd.[fire]                                           : {}", fpga_ctl->readReg(512+301));
    fmt::println("io.h2c_cmd.[fire]                                           : {}", fpga_ctl->readReg(512+302));
    fmt::println("io.c2h_data.[fire]                                          : {}", fpga_ctl->readReg(512+303));
    fmt::println("io.h2c_data.[fire]                                          : {}", fpga_ctl->readReg(512+304));
    fmt::println("fifo_c2h_cmd.io.out.[fire]                                  : {}", fpga_ctl->readReg(512+305));
    fmt::println("fifo_h2c_cmd.io.out.[fire]                                  : {}", fpga_ctl->readReg(512+306));
    fmt::println("fifo_c2h_data.io.out.[fire]                                 : {}", fpga_ctl->readReg(512+307));
    fmt::println("fifo_h2c_data.io.in.[fire]                                  : {}", fpga_ctl->readReg(512+308));

    //Report width 1:
    fmt::println("fifo_c2h_cmd.io.out.valid                                   : {}", (fpga_ctl->readReg(512+309) >> 0) & 1);
    fmt::println("fifo_c2h_cmd.io.out.ready                                   : {}", (fpga_ctl->readReg(512+309) >> 1) & 1);
    fmt::println("fifo_h2c_cmd.io.out.valid                                   : {}", (fpga_ctl->readReg(512+309) >> 2) & 1);
    fmt::println("fifo_h2c_cmd.io.out.ready                                   : {}", (fpga_ctl->readReg(512+309) >> 3) & 1);
    fmt::println("fifo_c2h_data.io.out.valid                                  : {}", (fpga_ctl->readReg(512+309) >> 4) & 1);
    fmt::println("fifo_c2h_data.io.out.ready                                  : {}", (fpga_ctl->readReg(512+309) >> 5) & 1);
    fmt::println("fifo_h2c_data.io.in.valid                                   : {}", (fpga_ctl->readReg(512+309) >> 6) & 1);
    fmt::println("fifo_h2c_data.io.in.ready                                   : {}", (fpga_ctl->readReg(512+309) >> 7) & 1);
}