#include <QDMAController.hpp>
#include "load.hpp"
#include <unistd.h>
#include <cstdio>

using namespace std;

void reset_counters(FPGACtl *fpga_ctl) {
    fpga_ctl->writeReg(14, 1);
    fpga_ctl->writeReg(14, 0);
}

void print_counters(FPGACtl *fpga_ctl) {
    // Print counters, copied from code generated by Chisel project.
    
    //Report width 32:
    fmt::println("tlb.io.tlb_miss_count                                       : {}", fpga_ctl->readReg(512+400));
    fmt::println("io.c2h_cmd.[fire]                                           : {}", fpga_ctl->readReg(512+401));
    fmt::println("io.h2c_cmd.[fire]                                           : {}", fpga_ctl->readReg(512+402));
    fmt::println("io.c2h_data.[fire]                                          : {}", fpga_ctl->readReg(512+403));
    fmt::println("io.h2c_data.[fire]                                          : {}", fpga_ctl->readReg(512+404));
    fmt::println("fifo_c2h_cmd.io.out.[fire]                                  : {}", fpga_ctl->readReg(512+405));
    fmt::println("fifo_h2c_cmd.io.out.[fire]                                  : {}", fpga_ctl->readReg(512+406));
    fmt::println("fifo_c2h_data.io.out.[fire]                                 : {}", fpga_ctl->readReg(512+407));
    fmt::println("fifo_h2c_data.io.in.[fire]                                  : {}", fpga_ctl->readReg(512+408));

    //Report width 1:
    fmt::println("fifo_c2h_cmd.io.out.valid                                   : {}", (fpga_ctl->readReg(512+409) >> 0) & 1);
    fmt::println("fifo_c2h_cmd.io.out.ready                                   : {}", (fpga_ctl->readReg(512+409) >> 1) & 1);
    fmt::println("fifo_h2c_cmd.io.out.valid                                   : {}", (fpga_ctl->readReg(512+409) >> 2) & 1);
    fmt::println("fifo_h2c_cmd.io.out.ready                                   : {}", (fpga_ctl->readReg(512+409) >> 3) & 1);
    fmt::println("fifo_c2h_data.io.out.valid                                  : {}", (fpga_ctl->readReg(512+409) >> 4) & 1);
    fmt::println("fifo_c2h_data.io.out.ready                                  : {}", (fpga_ctl->readReg(512+409) >> 5) & 1);
    fmt::println("fifo_h2c_data.io.in.valid                                   : {}", (fpga_ctl->readReg(512+409) >> 6) & 1);
    fmt::println("fifo_h2c_data.io.in.ready                                   : {}", (fpga_ctl->readReg(512+409) >> 7) & 1);
}

int main(void) {
    uint8_t pci_bus = 0x43;
    size_t size = 1UL*1024*1024*1024;
    
    FPGACtl::explictInit(pci_bus, 4 * 1024 * 1024);
    auto fpga_ctl = FPGACtl::getInstance(pci_bus);

    auto cpu_mem_ctl = CPUMemCtl::getInstance(1UL * 1024 * 1024 * 1024);

    cpu_mem_ctl->writeTLB([=](uint32_t page_index, uint32_t page_size, uint64_t vaddr, uint64_t paddr) {
        fpga_ctl->writeReg(8, (uint32_t) (vaddr));
        fpga_ctl->writeReg(9, (uint32_t) ((vaddr) >> 32));
        fpga_ctl->writeReg(10, (uint32_t) (paddr));
        fpga_ctl->writeReg(11, (uint32_t) ((paddr) >> 32));
        fpga_ctl->writeReg(12, (page_index == 0));
        fpga_ctl->writeReg(13, 1);
        fpga_ctl->writeReg(13, 0);
    });

    auto dma_buff = cpu_mem_ctl->alloc(size);
    
    uint32_t *H2CBuffer = (uint32_t * )(dma_buff);
    volatile uint32_t *C2HBuffer = (volatile uint32_t *) (H2CBuffer + 128L * 1024 * 1024);

    if (!startFpgaH2C(H2CBuffer, fpga_ctl) || !startFpgaC2H(C2HBuffer, fpga_ctl)) {
        print_counters(fpga_ctl);
        reset_counters(fpga_ctl);
        fmt::print(fg(fmt::color::red), "Aborted!\n");
        sleep(1);
        return 1;
    }
    print_counters(fpga_ctl);
    reset_counters(fpga_ctl);
    sleep(1);

    // AXIL Benchmark
    fmt::print(fg(fmt::color::cyan), "Axil Benchmark Begin!\n");

    uint32_t h2cTimeBegin, h2cTimeEnd, c2hTimeBegin, c2hTimeEnd, h2cTimeCount, c2hTimeCount;
    uint32_t h2cCommands, c2hCommands;
    double h2cBandwidth, c2hBandwidth;
    // read delay with no load
    h2cTimeBegin = fpga_ctl->readReg(H2C_TIME_COUNT);
    c2hTimeBegin = fpga_ctl->readReg(C2H_TIME_COUNT);
    auto readDelayWithNoLoad = axilReadBenchmark(fpga_ctl);
    h2cTimeEnd = fpga_ctl->readReg(H2C_TIME_COUNT);
    c2hTimeEnd = fpga_ctl->readReg(C2H_TIME_COUNT);
    h2cCommands = fpga_ctl->readReg(H2C_COMMANDS_CHECK);
    c2hCommands = fpga_ctl->readReg(C2H_COMMANDS_CHECK);
    h2cTimeCount = h2cTimeEnd - h2cTimeBegin;
    c2hTimeCount = c2hTimeEnd - c2hTimeBegin;
    h2cBandwidth = h2cCommands == 0 ? 0 : 1.0 * DEFAULT_DATA_BYTE_LENGTH * h2cCommands /
                                          (1.0 * h2cTimeCount * 4 / 1000 / 1000 / 1000) / 1024 / 1024 / 1024;
    c2hBandwidth = c2hCommands == 0 ? 0 : 1.0 * DEFAULT_DATA_BYTE_LENGTH * c2hCommands /
                                          (1.0 * c2hTimeCount * 4 / 1000 / 1000 / 1000) / 1024 / 1024 / 1024;
    fmt::println("Average Read Delay With No Load: {:.2f}ns ==> [QDMA]: H2C: {:.2f}GBps  C2H: {:.2f}GBps",
            readDelayWithNoLoad / 512.0, h2cBandwidth, c2hBandwidth);
    print_counters(fpga_ctl);
    reset_counters(fpga_ctl);
    sleep(1);


    // read with qdma H2C Load
    h2cTimeBegin = fpga_ctl->readReg(H2C_TIME_COUNT);
    c2hTimeBegin = fpga_ctl->readReg(C2H_TIME_COUNT);
    resumeFpgaH2C(fpga_ctl);
    auto readDelayWithH2CLoad = axilReadBenchmark(fpga_ctl);
    pauseFpgaH2C(fpga_ctl);
    sleep(2);
    h2cTimeEnd = fpga_ctl->readReg(H2C_TIME_COUNT);
    c2hTimeEnd = fpga_ctl->readReg(C2H_TIME_COUNT);
    h2cCommands = fpga_ctl->readReg(H2C_COMMANDS_CHECK);
    c2hCommands = fpga_ctl->readReg(C2H_COMMANDS_CHECK);
    h2cTimeCount = h2cTimeEnd - h2cTimeBegin;
    c2hTimeCount = c2hTimeEnd - c2hTimeBegin;
    h2cBandwidth = h2cCommands == 0 ? 0 : 1.0 * DEFAULT_DATA_BYTE_LENGTH * h2cCommands /
                                          (1.0 * h2cTimeCount * 4 / 1000 / 1000 / 1000) / 1024 / 1024 / 1024;
    c2hBandwidth = c2hCommands == 0 ? 0 : 1.0 * DEFAULT_DATA_BYTE_LENGTH * c2hCommands /
                                          (1.0 * c2hTimeCount * 4 / 1000 / 1000 / 1000) / 1024 / 1024 / 1024;
    fmt::println("Average Read Delay With H2C Load: {:.2f}ns ==> [QDMA]: H2C: {:.2f}GBps  C2H: {:.2f}GBps",
            readDelayWithH2CLoad / 512.0, h2cBandwidth, c2hBandwidth);
    print_counters(fpga_ctl);
    reset_counters(fpga_ctl);
    sleep(1);




    // read with qdma write load
    h2cTimeBegin = fpga_ctl->readReg(H2C_TIME_COUNT);
    c2hTimeBegin = fpga_ctl->readReg(C2H_TIME_COUNT);
    resumeFpgaC2H(fpga_ctl);
    auto readDelayWithC2HLoad = axilReadBenchmark(fpga_ctl);
    pauseFpgaC2H(fpga_ctl);
    sleep(2);
    h2cTimeEnd = fpga_ctl->readReg(H2C_TIME_COUNT);
    c2hTimeEnd = fpga_ctl->readReg(C2H_TIME_COUNT);
    h2cCommands = fpga_ctl->readReg(H2C_COMMANDS_CHECK);
    c2hCommands = fpga_ctl->readReg(C2H_COMMANDS_CHECK);
    h2cTimeCount = h2cTimeEnd - h2cTimeBegin;
    c2hTimeCount = c2hTimeEnd - c2hTimeBegin;
    h2cBandwidth = h2cCommands == 0 ? 0 : 1.0 * DEFAULT_DATA_BYTE_LENGTH * h2cCommands /
                                          (1.0 * h2cTimeCount * 4 / 1000 / 1000 / 1000) / 1024 / 1024 / 1024;
    c2hBandwidth = c2hCommands == 0 ? 0 : 1.0 * DEFAULT_DATA_BYTE_LENGTH * c2hCommands /
                                          (1.0 * c2hTimeCount * 4 / 1000 / 1000 / 1000) / 1024 / 1024 / 1024;
    fmt::println(stderr, "Average Read Delay With C2H Load: {:.2f}ns ==> [QDMA]: H2C: {:.2f}GBps  C2H: {:.2f}GBps",
            readDelayWithC2HLoad / 512.0, h2cBandwidth, c2hBandwidth);
    print_counters(fpga_ctl);
    reset_counters(fpga_ctl);
    sleep(1);



    // read with qdma read & write load
    h2cTimeBegin = fpga_ctl->readReg(H2C_TIME_COUNT);
    c2hTimeBegin = fpga_ctl->readReg(C2H_TIME_COUNT);
    resumeFpgaH2C(fpga_ctl);
    resumeFpgaC2H(fpga_ctl);
    auto readDelayWithH2CAndC2HLoad = axilReadBenchmark(fpga_ctl);
    pauseFpgaC2H(fpga_ctl);
    pauseFpgaH2C(fpga_ctl);
    sleep(2);
    h2cTimeEnd = fpga_ctl->readReg(H2C_TIME_COUNT);
    c2hTimeEnd = fpga_ctl->readReg(C2H_TIME_COUNT);
    h2cCommands = fpga_ctl->readReg(H2C_COMMANDS_CHECK);
    c2hCommands = fpga_ctl->readReg(C2H_COMMANDS_CHECK);
    h2cTimeCount = h2cTimeEnd - h2cTimeBegin;
    c2hTimeCount = c2hTimeEnd - c2hTimeBegin;
    h2cBandwidth = h2cCommands == 0 ? 0 : 1.0 * DEFAULT_DATA_BYTE_LENGTH * h2cCommands /
                                          (1.0 * h2cTimeCount * 4 / 1000 / 1000 / 1000) / 1024 / 1024 / 1024;
    c2hBandwidth = c2hCommands == 0 ? 0 : 1.0 * DEFAULT_DATA_BYTE_LENGTH * c2hCommands /
                                          (1.0 * c2hTimeCount * 4 / 1000 / 1000 / 1000) / 1024 / 1024 / 1024;
    fprintf(stderr, "Average Read Delay With H2C And C2H Load: %.2lfns ==> [QDMA]: H2C: %.2lfGBps  C2H: %.2lfGBps\n",
            readDelayWithH2CAndC2HLoad / 512.0, h2cBandwidth, c2hBandwidth);
    print_counters(fpga_ctl);
    reset_counters(fpga_ctl);
    sleep(1);

    fmt::print(fg(fmt::color::cyan), "Axil Benchmark Complete!\n");
}